# Generated by Django 5.2.14 on 2026-05-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integracoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('tipo', models.CharField(choices=[('classificador', 'Classificador'), ('extrator', 'Extrator'), ('validador', 'Validador'), ('estruturador', 'Estruturador'), ('generico', 'Generico')], max_length=30)),
                ('objetivo', models.TextField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('inativo', 'Inativo')], default='inativo', max_length=20)),
                ('prompt_base', models.TextField()),
                ('prompt_version', models.CharField(default='v1', max_length=30)),
                ('modelo_preferencial', models.CharField(blank=True, max_length=120)),
                ('parametros_execucao', models.JSONField(blank=True, default=dict)),
                ('permite_execucao_manual', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('openai_integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentes', to='integracoes.openaiintegration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente IA',
                'verbose_name_plural': 'Agentes IA',
                'indexes': [models.Index(fields=['status', 'tipo'], name='agentes_ia__status_2827ec_idx'), models.Index(fields=['openai_integration'], name='agentes_ia__openai__c6021e_idx')],
            },
        ),
    ]
