# Generated by Django 5.2.14 on 2026-05-23 19:46

import apps.agentes_ia.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_configuracoes_padrao(apps, schema_editor):
    agente_model = apps.get_model("agentes_ia", "AgenteIA")
    configuracao_model = apps.get_model(
        "agentes_ia",
        "AgenteConfiguracaoOperacional",
    )
    for agente in agente_model.objects.all():
        configuracao_model.objects.get_or_create(
            agente=agente,
            defaults={
                "input_policy": "escolhida_na_execucao",
                "default_input_source_type": "google_drive_folder",
                "allowed_input_extensions": ["pdf"],
                "allow_runtime_input_choice": True,
                "allow_runtime_file_upload": True,
                "output_policy": "configuravel_na_execucao",
                "default_output_format": "json",
                "default_output_destination": "internal_media",
                "allow_runtime_output_override": True,
                "runtime_fields_schema": {},
                "builder_schema": {},
                "concurrency_policy": {"block_parallel_per_agent": True},
            },
        )


def remover_configuracoes_padrao(apps, schema_editor):
    configuracao_model = apps.get_model(
        "agentes_ia",
        "AgenteConfiguracaoOperacional",
    )
    configuracao_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0002_rename_openai_integration_to_ai_provider_integration'),
        ('integracoes', '0005_localstorageintegration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteConfiguracaoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_policy', models.CharField(choices=[('fixa', 'Origem fixa'), ('escolhida_na_execucao', 'Escolhida na execucao'), ('upload_na_execucao', 'Upload na execucao'), ('sem_entrada', 'Sem entrada documental'), ('multipla', 'Multipla')], default='escolhida_na_execucao', max_length=40)),
                ('default_input_source_type', models.CharField(choices=[('google_drive_folder', 'Google Drive - pasta'), ('local_folder', 'Pasta local'), ('local_file', 'Arquivo local fixo'), ('upload_at_execution', 'Arquivo informado na execucao'), ('none', 'Sem origem documental')], default='google_drive_folder', max_length=40)),
                ('default_local_relative_input_path', models.CharField(blank=True, max_length=500)),
                ('allowed_input_extensions', models.JSONField(blank=True, default=apps.agentes_ia.models.default_allowed_input_extensions)),
                ('allow_runtime_input_choice', models.BooleanField(default=True)),
                ('allow_runtime_file_upload', models.BooleanField(default=True)),
                ('output_policy', models.CharField(choices=[('fixa', 'Saida fixa'), ('configuravel_na_execucao', 'Configuravel na execucao')], default='configuravel_na_execucao', max_length=40)),
                ('default_output_format', models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=20)),
                ('default_output_destination', models.CharField(choices=[('internal_media', 'Storage interno do sistema')], default='internal_media', max_length=40)),
                ('allow_runtime_output_override', models.BooleanField(default=True)),
                ('runtime_fields_schema', models.JSONField(blank=True, default=dict)),
                ('builder_schema', models.JSONField(blank=True, default=dict)),
                ('concurrency_policy', models.JSONField(blank=True, default=apps.agentes_ia.models.default_concurrency_policy)),
            ],
            options={
                'verbose_name': 'Configuracao operacional do agente',
                'verbose_name_plural': 'Configuracoes operacionais dos agentes',
            },
        ),
        migrations.AddField(
            model_name='agenteia',
            name='categoria_operacional',
            field=models.CharField(choices=[('leitura_documento', 'Leitura de documento'), ('decisao_documento', 'Decisao sobre documento'), ('acao_sistema', 'Acao de sistema'), ('leitura_arquivo', 'Leitura de arquivo'), ('generico', 'Generico')], default='leitura_documento', max_length=40),
        ),
        migrations.AddField(
            model_name='agenteia',
            name='clonado_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='agentes_ia.agenteia'),
        ),
        migrations.AddField(
            model_name='agenteia',
            name='modo_acionamento',
            field=models.CharField(choices=[('portal', 'Manual no portal'), ('botao_contextual', 'Botao contextual'), ('evento_sistema', 'Evento do sistema'), ('agendado', 'Agendado'), ('interno', 'Interno')], default='portal', max_length=40),
        ),
        migrations.AddField(
            model_name='agenteia',
            name='permite_clonagem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agenteia',
            name='visibilidade',
            field=models.CharField(choices=[('usuario', 'Agente para usuario'), ('tecnico', 'Agente tecnico')], default='usuario', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agenteia',
            index=models.Index(fields=['status', 'visibilidade'], name='agentes_ia__status_73275a_idx'),
        ),
        migrations.AddIndex(
            model_name='agenteia',
            index=models.Index(fields=['categoria_operacional'], name='agentes_ia__categor_176ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='agenteia',
            index=models.Index(fields=['modo_acionamento'], name='agentes_ia__modo_ac_d9f08a_idx'),
        ),
        migrations.AddIndex(
            model_name='agenteia',
            index=models.Index(fields=['clonado_de'], name='agentes_ia__clonado_c2cd04_idx'),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='agente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_operacional', to='agentes_ia.agenteia'),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='default_folder_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agentes_configuracao_padrao', to='integracoes.googledrivefoldersource'),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='default_local_storage_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agentes_configuracao_padrao', to='integracoes.localstorageintegration'),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agenteconfiguracaooperacional',
            index=models.Index(fields=['input_policy'], name='agentes_ia__input_p_475ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='agenteconfiguracaooperacional',
            index=models.Index(fields=['output_policy'], name='agentes_ia__output__bb33bf_idx'),
        ),
        migrations.AddIndex(
            model_name='agenteconfiguracaooperacional',
            index=models.Index(fields=['default_input_source_type', 'default_output_format'], name='agentes_conf_src_out_idx'),
        ),
        migrations.RunPython(
            criar_configuracoes_padrao,
            remover_configuracoes_padrao,
        ),
    ]
