# Generated by Django 5.2.14 on 2026-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0003_agenteconfiguracaooperacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='document_execution_mode',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupo_unico', 'Grupo unico'), ('lote_por_pasta', 'Lote por pasta')], default='individual', max_length=30),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='output_assembly_mode',
            field=models.CharField(choices=[('uma_por_entrada', 'Uma saida por entrada'), ('uma_por_grupo', 'Uma saida por grupo'), ('uma_saida_final', 'Uma saida final')], default='uma_por_entrada', max_length=30),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='output_packaging_mode',
            field=models.CharField(choices=[('arquivo_unico', 'Arquivo unico'), ('zip_se_multiplos', 'ZIP se multiplos'), ('sempre_zip', 'Sempre ZIP')], default='zip_se_multiplos', max_length=30),
        ),
    ]
