# Generated by Django 5.2.14 on 2026-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0004_agenteconfiguracaooperacional_document_execution_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='default_output_format',
            field=models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT')], default='json', max_length=20),
        ),
    ]
