# Generated by Django 5.2.14 on 2026-05-24 22:42

import apps.agentes_ia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0005_alter_agenteconfiguracaooperacional_default_output_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='prompt_parameters',
            field=models.JSONField(blank=True, default=apps.agentes_ia.models.default_prompt_parameters),
        ),
    ]
