# Generated by Django 5.2.14 on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentes_ia", "0006_agenteconfiguracaooperacional_prompt_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenteconfiguracaooperacional",
            name="default_output_format",
            field=models.CharField(
                choices=[
                    ("ai_defined", "Definido pela IA"),
                    ("json", "JSON"),
                    ("xlsx", "Excel"),
                    ("csv", "CSV"),
                    ("pdf", "PDF"),
                    ("txt", "TXT"),
                ],
                default="json",
                max_length=20,
            ),
        ),
    ]
