# Generated by Django 5.2.14 on 2026-05-28 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0007_alter_agenteconfiguracaooperacional_default_output_format'),
        ('integracoes', '0006_aiproviderintegration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='max_tentativas',
            field=models.PositiveSmallIntegerField(default=3, help_text='Numero maximo de tentativas de execucao por documento. 0 = sem limite.'),
        ),
        migrations.AddField(
            model_name='agenteia',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='default_output_destination',
            field=models.CharField(choices=[('internal_media', 'Pasta interna do sistema')], default='internal_media', max_length=40),
        ),
        migrations.AlterField(
            model_name='agenteia',
            name='ai_provider_integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentes', to='integracoes.aiproviderintegration'),
        ),
        migrations.CreateModel(
            name='VersaoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('versao', models.CharField(max_length=30)),
                ('prompt', models.TextField()),
                ('nota', models.TextField(blank=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes_prompt', to='agentes_ia.agenteia')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_prompt_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versao de prompt',
                'verbose_name_plural': 'Versoes de prompt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agente'], name='agentes_ia__agente__b04c11_idx')],
                'constraints': [models.UniqueConstraint(fields=('agente', 'versao'), name='unique_versao_prompt_por_agente')],
            },
        ),
    ]
