# Generated by Django 5.2.14 on 2026-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0008_agenteconfiguracaooperacional_max_tentativas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteia',
            name='objetivo',
            field=models.TextField(blank=True),
        ),
    ]
