# Generated by Django 5.2.15 on 2026-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0009_alter_agenteia_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='default_output_format',
            field=models.CharField(choices=[('ai_defined', 'Definido pela IA'), ('livre', 'Livre (saida direta da IA)'), ('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT')], default='json', max_length=20),
        ),
    ]
