# Generated by Django 5.2.15 on 2026-06-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0011_add_livre_output_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='document_execution_mode',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupo_unico', 'Grupo unico'), ('lote_por_pasta', 'Lote por sub-pastas')], default='individual', max_length=30),
        ),
    ]
