# Generated by Django 5.2.15 on 2026-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0012_alter_agenteconfiguracaooperacional_document_execution_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='default_output_format',
            field=models.CharField(choices=[('ai_defined', 'Definida pela IA'), ('livre', 'Definida pelo Prompt'), ('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT')], default='json', max_length=20),
        ),
    ]
