# Generated by Django 5.2.16 on 2026-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0014_agenteconfiguracaooperacional_default_gdrive_subfolder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='enable_pdf_preprocessing',
            field=models.BooleanField(default=False, help_text='Antes de enviar o PDF para a IA, remove paginas duplicadas ou quase-duplicadas e ignora cabecalhos/rodapes repetidos na comparacao, reduzindo tokens e custo. So afeta documentos PDF.'),
        ),
    ]
