# Generated by Django 5.2.16 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0015_agenteconfiguracaooperacional_enable_pdf_preprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='enable_thinking_budget_reduction',
            field=models.BooleanField(default=False, help_text="Reduz o custo de 'raciocinio' interno da IA antes de responder (tokens cobrados mas nunca exibidos). Corta custo, mas reduz a profundidade de analise da IA — valide as respostas antes de confiar em producao, especialmente em itens que exigem julgamento mais fino."),
        ),
    ]
