# Generated by Django 5.2.16 on 2026-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0016_agenteconfiguracaooperacional_enable_thinking_budget_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='include_subfolders',
            field=models.BooleanField(default=False, help_text="Le os PDFs de todas as subpastas abaixo da pasta raiz configurada (Google Drive ou pasta local), em qualquer nivel — nao so os arquivos soltos na raiz. So tem efeito quando a origem padrao e 'Google Drive - pasta' ou 'Pasta local'. Para pastas com muitos documentos, o processamento e feito em lotes automaticos para nao travar a execucao."),
        ),
    ]
