# Generated by Django 5.2.16 on 2026-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0017_agenteconfiguracaooperacional_include_subfolders'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='allowed_filename_pattern',
            field=models.CharField(blank=True, help_text="Padrao estilo 'Edital*' (aceita * em qualquer posicao) para filtrar pelo NOME do arquivo antes de enviar para a IA — arquivos que nao baterem o padrao sao descartados sem serem lidos nem enviados. Sem diferenciar mai/minusculas. Deixe em branco para nao filtrar por nome. So se aplica quando a origem padrao e uma pasta (Google Drive ou local).", max_length=200),
        ),
    ]
