# Generated by Django 5.2.17 on 2026-08-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0018_agenteconfiguracaooperacional_allowed_filename_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='allowed_filename_pattern',
            field=models.CharField(blank=True, help_text="Padrão estilo 'Edital*' (aceita * em qualquer posição) para filtrar pelo NOME do arquivo antes de enviar para a IA — arquivos que não baterem o padrão são descartados sem serem lidos nem enviados. Sem diferenciar maiúsculas/minúsculas. Deixe em branco para não filtrar por nome. Só se aplica quando a origem padrão é uma pasta (Google Drive ou local).", max_length=200),
        ),
    ]
