# Generated by Django 5.2.17 on 2026-08-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0019_alter_agenteconfiguracaooperacional_allowed_filename_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_ativa',
            field=models.BooleanField(default=False, help_text='Processa automaticamente um lote pequeno de documentos pendentes a cada X minutos, em vez de depender de alguem clicar Executar. Util para pastas com muitos documentos (ex.: 40-50 de uma vez), que nao cabem numa unica execucao sem estourar o tempo limite do servidor. Se nao houver nada novo, a rotina nao faz nada nessa rodada.'),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_intervalo_minutos',
            field=models.PositiveSmallIntegerField(default=60, help_text='Intervalo entre rodadas da rotina automatica, em minutos.'),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_lote_tamanho',
            field=models.PositiveSmallIntegerField(default=10, help_text='Quantos documentos pendentes a rotina automatica processa por rodada. Os demais ficam pendentes para a rodada seguinte.'),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_proxima_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_em_andamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_em_andamento_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
