# Generated by Django 5.2.17 on 2026-08-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0020_agenteconfiguracaooperacional_execucao_automatica_ativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_ativa',
            field=models.BooleanField(default=False, help_text='Processa automaticamente um lote pequeno de documentos pendentes a cada X minutos, em vez de depender de alguém clicar Executar. Útil para pastas com muitos documentos (ex.: 40-50 de uma vez), que não cabem numa única execução sem estourar o tempo limite do servidor. Se não houver nada novo, a rotina não faz nada nessa rodada.'),
        ),
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_intervalo_minutos',
            field=models.PositiveSmallIntegerField(default=60, help_text='Intervalo entre rodadas da rotina automática, em minutos.'),
        ),
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_lote_tamanho',
            field=models.PositiveSmallIntegerField(default=10, help_text='Quantos documentos pendentes a rotina automática processa por rodada. Os demais ficam pendentes para a rodada seguinte.'),
        ),
    ]
