# Generated by Django 5.2.17 on 2026-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0021_alter_agenteconfiguracaooperacional_execucao_automatica_ativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_intervalo_minutos',
        ),
        migrations.RemoveField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_proxima_em',
        ),
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_lote_tamanho',
            field=models.PositiveSmallIntegerField(default=10, help_text='Quantos documentos pendentes a rotina automática processa por rodada. Os demais ficam pendentes para a rodada seguinte. Se o intervalo global (definido em Administrador > Rotina automática) for menor que 30 minutos, esse valor é ignorado e a rotina processa no máximo 6 documentos por rodada, para todos os agentes.'),
        ),
    ]
