# Generated by Django 5.2.17 on 2026-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0022_remove_agenteconfiguracaooperacional_execucao_automatica_intervalo_minutos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_lote_tamanho',
        ),
        migrations.AlterField(
            model_name='agenteconfiguracaooperacional',
            name='execucao_automatica_ativa',
            field=models.BooleanField(default=False, help_text='Processa automaticamente um lote pequeno de documentos pendentes a cada X minutos, em vez de depender de alguém clicar Executar. Útil para pastas com muitos documentos (ex.: 40-50 de uma vez), que não cabem numa única execução sem estourar o tempo limite do servidor. O intervalo entre rodadas e quantos documentos cada rodada processa são definidos em Administrador > Rotina automática, valendo para todos os agentes participantes. Se não houver nada novo, a rotina não faz nada nessa rodada.'),
        ),
    ]
