# Generated by Django 5.2.14 on 2026-05-22 18:19

import apps.processamentos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentes_ia', '0001_initial'),
        ('integracoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('em_fila', 'Em fila'), ('em_processamento', 'Em processamento'), ('concluido_sucesso', 'Concluido com sucesso'), ('concluido_erro', 'Concluido com erro'), ('cancelado', 'Cancelado')], default='criado', max_length=30)),
                ('drive_folder_id_escolhida', models.CharField(max_length=255)),
                ('drive_folder_nome_escolhida', models.CharField(blank=True, max_length=255)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('modelo_snapshot', models.CharField(blank=True, max_length=120)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('total_documentos', models.PositiveIntegerField(default=0)),
                ('total_processados', models.PositiveIntegerField(default=0)),
                ('arquivo_saida', models.FileField(blank=True, null=True, upload_to=apps.processamentos.models.processamento_output_path)),
                ('arquivo_saida_nome', models.CharField(blank=True, max_length=255)),
                ('arquivo_saida_formato', models.CharField(default='xlsx', max_length=20)),
                ('arquivo_saida_liberado_em', models.DateTimeField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processamentos', to='agentes_ia.agenteia')),
                ('google_drive_integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processamentos', to='integracoes.googledriveintegration')),
                ('iniciado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processamentos_iniciados', to=settings.AUTH_USER_MODEL)),
                ('openai_integration_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processamentos_snapshot', to='integracoes.openaiintegration')),
            ],
            options={
                'verbose_name': 'Processamento',
                'verbose_name_plural': 'Processamentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('drive_file_id', models.CharField(max_length=255)),
                ('drive_path', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_processamento', 'Em processamento'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processamentos.processamento')),
            ],
            options={
                'verbose_name': 'Documento de entrada',
                'verbose_name_plural': 'Documentos de entrada',
            },
        ),
        migrations.AddIndex(
            model_name='processamento',
            index=models.Index(fields=['status'], name='processamen_status_a0f883_idx'),
        ),
        migrations.AddIndex(
            model_name='processamento',
            index=models.Index(fields=['iniciado_por'], name='processamen_iniciad_115b79_idx'),
        ),
        migrations.AddIndex(
            model_name='processamento',
            index=models.Index(fields=['agente'], name='processamen_agente__fcdb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='processamento',
            index=models.Index(fields=['google_drive_integration'], name='processamen_google__915380_idx'),
        ),
        migrations.AddIndex(
            model_name='processamento',
            index=models.Index(fields=['iniciado_em'], name='processamen_iniciad_0d0d03_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoentrada',
            index=models.Index(fields=['processamento'], name='processamen_process_f52bca_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoentrada',
            index=models.Index(fields=['drive_file_id'], name='processamen_drive_f_4f7b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoentrada',
            index=models.Index(fields=['processamento', 'status'], name='processamen_process_7e6072_idx'),
        ),
    ]
