# Generated by Django 5.2.14 on 2026-05-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_alter_googledriveintegration_drive_folder_id_and_more'),
        ('processamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='drive_folder_url_escolhida',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='processamento',
            name='folder_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processamentos', to='integracoes.googledrivefoldersource'),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='drive_folder_id_escolhida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='google_drive_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processamentos', to='integracoes.googledriveintegration'),
        ),
    ]
