# Generated by Django 5.2.14 on 2026-05-23 10:58

import apps.processamentos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0002_rename_openai_integration_to_ai_provider_integration'),
        ('integracoes', '0005_localstorageintegration'),
        ('processamentos', '0005_processamentoexecucaoia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSaidaProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formato', models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=20)),
                ('status', models.CharField(choices=[('gerado', 'Gerado'), ('erro', 'Erro')], default='gerado', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=apps.processamentos.models.documento_saida_output_path)),
                ('arquivo_nome', models.CharField(blank=True, max_length=255)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('liberado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Saida de documento do processamento',
                'verbose_name_plural': 'Saidas de documento do processamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentoentrada',
            name='source_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documentoentrada',
            name='source_type',
            field=models.CharField(choices=[('google_drive_folder', 'Google Drive - pasta'), ('local_folder', 'Pasta local'), ('local_file', 'Arquivo local fixo'), ('upload_at_execution', 'Arquivo informado na execucao')], default='google_drive_folder', max_length=30),
        ),
        migrations.AddField(
            model_name='documentoentrada',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.processamentos.models.documento_entrada_upload_path),
        ),
        migrations.AddField(
            model_name='processamento',
            name='arquivo_execucao_upload',
            field=models.FileField(blank=True, null=True, upload_to=apps.processamentos.models.processamento_input_upload_path),
        ),
        migrations.AddField(
            model_name='processamento',
            name='input_source_type',
            field=models.CharField(choices=[('google_drive_folder', 'Google Drive - pasta'), ('local_folder', 'Pasta local'), ('local_file', 'Arquivo local fixo'), ('upload_at_execution', 'Arquivo informado na execucao')], default='google_drive_folder', max_length=30),
        ),
        migrations.AddField(
            model_name='processamento',
            name='local_relative_input_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='processamento',
            name='local_storage_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processamentos', to='integracoes.localstorageintegration'),
        ),
        migrations.AddField(
            model_name='processamento',
            name='output_format',
            field=models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentoentrada',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='documentoentrada',
            index=models.Index(fields=['processamento', 'source_type'], name='processamen_process_925e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='processamento',
            index=models.Index(fields=['input_source_type'], name='processamen_input_s_408ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='processamento',
            index=models.Index(fields=['local_storage_integration'], name='processamen_local_s_71d7d6_idx'),
        ),
        migrations.AddField(
            model_name='documentosaidaprocessamento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='processamentos.documentoentrada'),
        ),
        migrations.AddField(
            model_name='documentosaidaprocessamento',
            name='execucao_ia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_saida', to='processamentos.processamentoexecucaoia'),
        ),
        migrations.AddField(
            model_name='documentosaidaprocessamento',
            name='processamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_saida', to='processamentos.processamento'),
        ),
        migrations.AddIndex(
            model_name='documentosaidaprocessamento',
            index=models.Index(fields=['processamento'], name='processamen_process_c53994_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosaidaprocessamento',
            index=models.Index(fields=['documento'], name='processamen_documen_867f74_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosaidaprocessamento',
            index=models.Index(fields=['processamento', 'status'], name='processamen_process_32b9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosaidaprocessamento',
            index=models.Index(fields=['processamento', 'formato'], name='processamen_process_d660f1_idx'),
        ),
    ]
