# Generated by Django 5.2.14 on 2026-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0006_documentosaidaprocessamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoentrada',
            name='source_type',
            field=models.CharField(choices=[('google_drive_folder', 'Google Drive - pasta'), ('local_folder', 'Pasta local'), ('local_file', 'Arquivo local fixo'), ('upload_at_execution', 'Arquivo informado na execucao'), ('none', 'Sem origem documental')], default='google_drive_folder', max_length=30),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='input_source_type',
            field=models.CharField(choices=[('google_drive_folder', 'Google Drive - pasta'), ('local_folder', 'Pasta local'), ('local_file', 'Arquivo local fixo'), ('upload_at_execution', 'Arquivo informado na execucao'), ('none', 'Sem origem documental')], default='google_drive_folder', max_length=30),
        ),
    ]
