# Generated by Django 5.2.14 on 2026-05-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0009_migrar_erros_tecnicos_processamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosaidaprocessamento',
            name='documentos_referencia',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentosaidaprocessamento',
            name='scope_type',
            field=models.CharField(choices=[('sem_documento', 'Sem documento'), ('individual', 'Individual'), ('grupo', 'Grupo')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='processamento',
            name='document_execution_mode_snapshot',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupo_unico', 'Grupo unico'), ('lote_por_pasta', 'Lote por pasta')], default='individual', max_length=30),
        ),
        migrations.AddField(
            model_name='processamento',
            name='output_assembly_mode_snapshot',
            field=models.CharField(choices=[('uma_por_entrada', 'Uma saida por entrada'), ('uma_por_grupo', 'Uma saida por grupo'), ('uma_saida_final', 'Uma saida final')], default='uma_por_entrada', max_length=30),
        ),
        migrations.AddField(
            model_name='processamento',
            name='output_packaging_mode_snapshot',
            field=models.CharField(choices=[('arquivo_unico', 'Arquivo unico'), ('zip_se_multiplos', 'ZIP se multiplos'), ('sempre_zip', 'Sempre ZIP')], default='zip_se_multiplos', max_length=30),
        ),
        migrations.AddField(
            model_name='processamentoexecucaoia',
            name='documentos_referencia',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='processamentoexecucaoia',
            name='scope_type',
            field=models.CharField(choices=[('sem_documento', 'Sem documento'), ('individual', 'Individual'), ('grupo', 'Grupo')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosaidaprocessamento',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='processamentos.documentoentrada'),
        ),
        migrations.AlterField(
            model_name='documentosaidaprocessamento',
            name='formato',
            field=models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='output_format',
            field=models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
    ]
