# Generated by Django 5.2.14 on 2026-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0010_documentosaidaprocessamento_documentos_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='documento_atual_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processamento',
            name='etapa_atual',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='processamento',
            name='ultima_atividade_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
