# Generated by Django 5.2.14 on 2026-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0011_processamento_documento_atual_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosaidaprocessamento',
            name='formato',
            field=models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='output_format',
            field=models.CharField(choices=[('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
    ]
