# Generated by Django 5.2.14 on 2026-05-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0006_aiproviderintegration_and_more'),
        ('processamentos', '0013_alter_output_format_ai_defined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosaidaprocessamento',
            name='documentos_referencia',
        ),
        migrations.RemoveField(
            model_name='processamentoexecucaoia',
            name='documentos_referencia',
        ),
        migrations.AddField(
            model_name='documentosaidaprocessamento',
            name='documentos_entrada',
            field=models.ManyToManyField(blank=True, related_name='saidas_como_referencia', to='processamentos.documentoentrada'),
        ),
        migrations.AddField(
            model_name='processamento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='processamentoexecucaoia',
            name='documentos_entrada',
            field=models.ManyToManyField(blank=True, related_name='execucoes_como_referencia', to='processamentos.documentoentrada'),
        ),
        migrations.AlterField(
            model_name='documentosaidaprocessamento',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='processamentos.documentoentrada'),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='ai_provider_integration_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processamentos_snapshot', to='integracoes.aiproviderintegration'),
        ),
        migrations.AlterField(
            model_name='processamentoexecucaoia',
            name='ai_provider_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_processamento', to='integracoes.aiproviderintegration'),
        ),
    ]
