# Generated by Django 5.2.14 on 2026-05-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0014_remove_documentosaidaprocessamento_documentos_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoentrada',
            name='pasta_grupo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
