# Generated by Django 5.2.15 on 2026-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0019_set_null_integracoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='document_execution_mode_snapshot',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupo_unico', 'Grupo unico'), ('lote_por_pasta', 'Lote por sub-pastas')], default='individual', max_length=30),
        ),
    ]
