# Generated by Django 5.2.15 on 2026-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0020_alter_processamento_document_execution_mode_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosaidaprocessamento',
            name='formato',
            field=models.CharField(choices=[('ai_defined', 'Definido pela IA'), ('livre', 'Livre (saida direta da IA)'), ('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='output_format',
            field=models.CharField(choices=[('ai_defined', 'Definido pela IA'), ('livre', 'Livre (saida direta da IA)'), ('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
    ]
