# Generated by Django 5.2.15 on 2026-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0021_add_livre_output_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('em_fila', 'Em fila'), ('em_processamento', 'Em processamento'), ('concluido_sucesso', 'Concluido com sucesso'), ('concluido_erro', 'Concluido com erro'), ('concluido_atencao', 'Concluido com atencao'), ('cancelado', 'Cancelado')], default='criado', max_length=30),
        ),
    ]
