# Generated by Django 5.2.15 on 2026-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0023_add_concluido_atencao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosaidaprocessamento',
            name='formato',
            field=models.CharField(choices=[('ai_defined', 'Definida pela IA'), ('livre', 'Definida pelo Prompt'), ('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='output_format',
            field=models.CharField(choices=[('ai_defined', 'Definida pela IA'), ('livre', 'Definida pelo Prompt'), ('json', 'JSON'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('txt', 'TXT'), ('zip', 'ZIP')], default='json', max_length=20),
        ),
    ]
