# Generated by Django 5.2.15 on 2026-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0025_filefield_max_length_255'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoentrada',
            name='erro_reprocessavel',
            field=models.BooleanField(default=True),
        ),
    ]
