# Generated by Django 5.2.16 on 2026-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0026_documentoentrada_erro_reprocessavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='progresso_etapa_percentual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
