# Generated by Django 5.2.16 on 2026-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0027_processamento_progresso_etapa_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='forcar_reprocessamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='documentoentrada',
            index=models.Index(fields=['nome_arquivo'], name='processamen_nome_ar_e91b72_idx'),
        ),
    ]
