# Generated by Django 5.2.16 on 2026-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0028_processamento_forcar_reprocessamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='total_documentos_ignorados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
