# Generated by Django 5.2.16 on 2026-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0029_processamento_total_documentos_ignorados'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='atingiu_limite_lote_subpastas',
            field=models.BooleanField(default=False),
        ),
    ]
