# Generated by Django 5.2.17 on 2026-08-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0030_processamento_atingiu_limite_lote_subpastas'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='retentativa_sobrecarga_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processamento',
            name='retentativa_sobrecarga_iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processamento',
            name='retentativa_sobrecarga_proxima_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processamento',
            name='retentativa_sobrecarga_tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
