# Generated by Django 5.2.17 on 2026-08-20 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes_ia', '0022_remove_agenteconfiguracaooperacional_execucao_automatica_intervalo_minutos_and_more'),
        ('processamentos', '0031_processamento_retentativa_sobrecarga_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaAutomaticaExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('executada', 'Executada'), ('sem_documentos', 'Sem documentos novos'), ('bloqueada', 'Agente ja em execucao'), ('erro', 'Erro ao iniciar')], max_length=20)),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('total_documentos', models.PositiveSmallIntegerField(default=0)),
                ('total_sucesso', models.PositiveSmallIntegerField(default=0)),
                ('total_erro', models.PositiveSmallIntegerField(default=0)),
                ('motivo', models.TextField(blank=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_rotina_automatica', to='agentes_ia.agenteia')),
                ('processamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucao_rotina_automatica_origem', to='processamentos.processamento')),
            ],
            options={
                'verbose_name': 'Execucao da rotina automatica',
                'verbose_name_plural': 'Execucoes da rotina automatica',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['agente', '-iniciado_em'], name='processamen_agente__0674db_idx'), models.Index(fields=['status'], name='processamen_status_e71dcb_idx')],
            },
        ),
    ]
