# Generated by Django 5.2.16 on 2026-08-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0032_rotinaautomaticaexecucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoentrada',
            name='tentativas_pontuais',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rotinaautomaticaexecucao',
            name='total_pendente',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='documentoentrada',
            index=models.Index(fields=['status', 'tentativas_pontuais'], name='processamen_status_8cea04_idx'),
        ),
    ]
