# Generated by Django 5.2.16 on 2026-08-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0033_documentoentrada_tentativas_pontuais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='bloqueado_permanentemente',
            field=models.BooleanField(default=False),
        ),
    ]
