# Generated by Django 5.2.16 on 2026-08-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0034_processamento_bloqueado_permanentemente'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamento',
            name='rotina_automatica_execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processamentos_da_rodada', to='processamentos.rotinaautomaticaexecucao'),
        ),
    ]
