# Generated by Django 5.2.16 on 2026-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamentos', '0035_processamento_rotina_automatica_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('em_fila', 'Em fila'), ('em_processamento', 'Em processamento'), ('concluido_sucesso', 'Concluido com sucesso'), ('concluido_erro', 'Concluido com erro'), ('concluido_atencao', 'Concluido com atencao'), ('cancelado', 'Cancelado'), ('pendente_retentativa', 'Aguardando proxima rotina')], default='criado', max_length=30),
        ),
    ]
