# Generated by Django 5.2.15 on 2026-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_limpeza_data_programada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaogeral',
            name='data_programada_limpeza',
            field=models.DateField(blank=True, help_text='Na data escolhida, a meia-noite, o sistema apagara todos os arquivos de saida com mais de 30 dias. Apos executar, este campo e limpo automaticamente.', null=True),
        ),
    ]
