# Generated by Django 5.2.15 on 2026-06-07 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_add_dia_execucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('grupos', models.ManyToManyField(blank=True, related_name='permissoes_menu', to='auth.group')),
                ('usuarios_extras', models.ManyToManyField(blank=True, related_name='permissoes_menu_extras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissao de menu',
                'verbose_name_plural': 'Permissoes de menu',
                'ordering': ['ordem', 'label'],
            },
        ),
    ]
