# Generated by Django 5.2.15 on 2026-06-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_permissao_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaogeral',
            name='dia_execucao_limpeza',
            field=models.PositiveSmallIntegerField(default=30, help_text='Dia do mes em que a limpeza e executada (ex: 30 = todo dia 30 de cada mes).'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='dias_retencao_arquivos',
            field=models.PositiveIntegerField(default=30, help_text='Arquivos com mais de N dias serao deletados na execucao.'),
        ),
    ]
