# Generated by Django 5.2.15 on 2026-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_configuracaogeral_dia_execucao_limpeza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='max_execucoes_por_usuario',
            field=models.PositiveSmallIntegerField(default=2, help_text='Maximo de execucoes simultaneas por usuario. 0 = sem limite.'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='max_execucoes_simultaneas',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximo de execucoes simultaneas no sistema inteiro. 0 = sem limite.'),
        ),
    ]
