# Generated by Django 5.2.16 on 2026-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_mascote_ativo_configuracao_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='max_pdfs_lote_subpastas',
            field=models.PositiveSmallIntegerField(default=25, help_text='Maximo de PDFs processados por lote quando um agente le subpastas recursivamente. 0 = sem limite.'),
        ),
    ]
