# Generated by Django 5.2.17 on 2026-08-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracaogeral_max_pdfs_lote_subpastas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='intervalo_entre_documentos_ia_segundos',
            field=models.PositiveSmallIntegerField(default=2, help_text='Segundos de espera entre o processamento de um documento e o proximo, quando um agente processa varios documentos em sequencia. Reduz a chance de estourar o limite de requisicoes por minuto do provedor de IA em lotes grandes. 0 = sem espera.'),
        ),
    ]
