# Generated by Django 5.2.17 on 2026-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracaogeral_intervalo_entre_documentos_ia_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_agentes_ativa',
            field=models.BooleanField(default=True, help_text='Liga ou desliga a rotina automatica de execucao de agentes em todo o sistema. Quando desligada, nenhum agente processa documentos automaticamente, mesmo que tenha a rotina ativada individualmente nas suas configuracoes.'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_intervalo_minutos',
            field=models.PositiveSmallIntegerField(default=60, help_text='Intervalo entre rodadas da rotina automatica, em minutos (minimo 10, maximo 1440 = 24h). Vale para todos os agentes com a rotina ativada. Se for menor que 30 minutos, cada rodada processa no maximo 6 documentos por agente.'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_proxima_execucao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
