# Generated by Django 5.2.17 on 2026-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configuracaogeral_rotina_automatica_agentes_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_lote_tamanho',
            field=models.PositiveSmallIntegerField(default=10, help_text='Quantos documentos pendentes cada agente participante da rotina automatica processa por rodada. Os demais ficam pendentes para a rodada seguinte. Vale para todos os agentes com a rotina ativada. Ignorado (fixo em 6) quando o intervalo entre rodadas for menor que 30 minutos.'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='rotina_automatica_intervalo_minutos',
            field=models.PositiveSmallIntegerField(default=60, help_text='Intervalo entre rodadas da rotina automatica, em minutos (minimo 10, maximo 1440 = 24h). Vale para todos os agentes com a rotina ativada. Se for menor que 30 minutos, cada rodada processa no maximo 6 documentos por agente, ignorando rotina_automatica_lote_tamanho.'),
        ),
    ]
