# Generated by Django 5.2.17 on 2026-08-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_configuracaogeral_rotina_automatica_lote_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_inicio_em',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a primeira rodada apos salvar essa configuracao deve acontecer (ex.: 20/08/2026 as 19:20). Depois dessa primeira rodada, as demais seguem so o intervalo configurado acima. Deixe em branco para nao agendar um inicio especifico.', null=True),
        ),
    ]
