# Generated by Django 5.2.17 on 2026-08-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_configuracaogeral_rotina_automatica_inicio_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_ultima_verificacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
