# Generated by Django 5.2.16 on 2026-08-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configuracaogeral_rotina_automatica_ultima_verificacao_em'),
        ('integracoes', '0012_encrypt_existing_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_ai_provider_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integracoes.aiproviderintegration'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_ia_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_ia_modelo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
