# Generated by Django 5.2.16 on 2026-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_configuracaogeral_biel_ai_provider_integration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_custo_brl_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_custo_usd_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_tokens_input_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_tokens_output_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='biel_uso_zerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
