# Generated by Django 5.2.16 on 2026-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_configuracaogeral_biel_custo_brl_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_em_execucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='rotina_automatica_em_execucao_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
