# Generated by Django 5.2.14 on 2026-05-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('erro', 'Erro')], default='inativa', max_length=20)),
                ('auth_mode', models.CharField(default='service_account', max_length=30)),
                ('drive_folder_id', models.CharField(max_length=255)),
                ('credentials_json', models.TextField()),
                ('service_account_email', models.EmailField(max_length=254)),
                ('allowed_extensions', models.JSONField(blank=True, default=list)),
                ('last_connection_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integracao Google Drive',
                'verbose_name_plural': 'Integracoes Google Drive',
                'indexes': [models.Index(fields=['status'], name='integracoes_status_27c912_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenAIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('erro', 'Erro')], default='inativa', max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('api_base_url', models.URLField(blank=True)),
                ('organization_id', models.CharField(blank=True, max_length=120)),
                ('project_id', models.CharField(blank=True, max_length=120)),
                ('default_model', models.CharField(blank=True, max_length=120)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('last_connection_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integracao OpenAI',
                'verbose_name_plural': 'Integracoes OpenAI',
                'indexes': [models.Index(fields=['status'], name='integracoes_status_716391_idx')],
            },
        ),
    ]
