# Generated by Django 5.2.14 on 2026-05-22 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledriveintegration',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='GoogleDriveFolderSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('erro', 'Erro')], default='ativa', max_length=20)),
                ('folder_url', models.URLField()),
                ('folder_id', models.CharField(editable=False, max_length=255)),
                ('folder_display_name', models.CharField(blank=True, max_length=255)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('google_drive_integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folder_sources', to='integracoes.googledriveintegration')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Origem de pasta Google Drive',
                'verbose_name_plural': 'Origens de pasta Google Drive',
                'indexes': [models.Index(fields=['status'], name='integracoes_status_3c3058_idx'), models.Index(fields=['folder_id'], name='integracoes_folder__623133_idx')],
                'constraints': [models.UniqueConstraint(fields=('google_drive_integration', 'folder_id'), name='unique_folder_source_by_integration')],
            },
        ),
    ]
