# Generated by Django 5.2.14 on 2026-05-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_alter_googledriveintegration_drive_folder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveFolderSourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_item_id', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('item_type', models.CharField(choices=[('pasta', 'Pasta'), ('pdf', 'PDF'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('parent_drive_id', models.CharField(blank=True, max_length=255)),
                ('web_view_link', models.URLField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disponivel_para_ia', models.BooleanField(default=False)),
                ('sincronizado_em', models.DateTimeField()),
                ('folder_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_items', to='integracoes.googledrivefoldersource')),
            ],
            options={
                'verbose_name': 'Item sincronizado da origem Google Drive',
                'verbose_name_plural': 'Itens sincronizados da origem Google Drive',
                'ordering': ['item_type', 'nome'],
                'indexes': [models.Index(fields=['folder_source'], name='integracoes_folder__c7cd7e_idx'), models.Index(fields=['drive_item_id'], name='integracoes_drive_i_c3a283_idx'), models.Index(fields=['folder_source', 'item_type'], name='integracoes_folder__324375_idx'), models.Index(fields=['folder_source', 'disponivel_para_ia'], name='integracoes_folder__91c25c_idx')],
                'constraints': [models.UniqueConstraint(fields=('folder_source', 'drive_item_id'), name='unique_folder_source_drive_item')],
            },
        ),
    ]
