# Generated by Django 5.2.15 on 2026-06-07 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0010_pastacompartilhadausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='localstorageintegration',
            name='usuarios_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Usuários que podem usar esta pasta. Vazio = somente administradores.', related_name='integracoes_pasta_autorizada', through='integracoes.PastaCompartilhadaUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastacompartilhadausuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
