# Generated by Django 5.2.14 on 2026-05-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modulo', models.CharField(max_length=40)),
                ('acao', models.CharField(max_length=60)),
                ('objeto_tipo', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(max_length=64)),
                ('descricao', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
                ('processamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='processamentos.processamento')),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'indexes': [models.Index(fields=['modulo'], name='auditoria_e_modulo_bd2cac_idx'), models.Index(fields=['actor'], name='auditoria_e_actor_i_36562c_idx'), models.Index(fields=['processamento'], name='auditoria_e_process_615822_idx'), models.Index(fields=['created_at'], name='auditoria_e_created_bdc119_idx')],
            },
        ),
    ]
